name: PRPreview

on:
  pull_request:
    types: [opened, reopened]

jobs:
  Check:
    runs-on: ubuntu-latest 
    steps:
      - name: Comment to PR
        uses: JoseThen/comment-pr@v1.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.ghtoken }}
          comment: |
            ## Thanks for your contribution
            
            **This message was sent automatically by CI**

            we are checking your code and later we will send you a preview link for your code here

            have a nice day~

  Preview:
    needs: Check
    runs-on: ubuntu-latest
    steps:
      - name: Get PR ID
        run: echo PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }') >> $GITHUB_ENV
      - name: Comment to PR
        uses: JoseThen/comment-pr@v1.1.1
        with:
          GITHUB_TOKEN: ${{ secrets.ghtoken }}
          comment: |
            ## Check Passed! > <
            
            The code check has already passed!!!

            Here is your preview link, check and close your Pr immediately if it doesn't meet your expectations.

            [Check Your Code](https://prev.lancex.top/dspd/${{ env.PR_NUMBER }})

            Soon we will check and merge it, wait please :)